"""add location to almoxitem

Revision ID: 2beaf152125e
Revises: f65c14090ffe
Create Date: 2026-06-22 11:12:08.160562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beaf152125e'
down_revision = 'f65c14090ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=180), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_items', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
