"""add_shelf_and_shelf_level_tables

Revision ID: d22bcc498853
Revises: 2beaf152125e
Create Date: 2026-06-22 12:24:16.820069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22bcc498853'
down_revision = '2beaf152125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelves_name'), ['name'], unique=True)

    op.create_table('shelf_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'label', name='uq_shelf_level_label')
    )
    with op.batch_alter_table('shelf_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_levels_shelf_id'), ['shelf_id'], unique=False)

    with op.batch_alter_table('almox_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shelf_level_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_almox_items_shelf_id'), ['shelf_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_almox_items_shelf_level_id'), ['shelf_level_id'], unique=False)
        batch_op.create_foreign_key('fk_almox_items_shelf_id', 'shelves', ['shelf_id'], ['id'])
        batch_op.create_foreign_key('fk_almox_items_shelf_level_id', 'shelf_levels', ['shelf_level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almox_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_almox_items_shelf_level_id', type_='foreignkey')
        batch_op.drop_constraint('fk_almox_items_shelf_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_almox_items_shelf_level_id'))
        batch_op.drop_index(batch_op.f('ix_almox_items_shelf_id'))
        batch_op.drop_column('shelf_level_id')
        batch_op.drop_column('shelf_id')

    with op.batch_alter_table('shelf_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_levels_shelf_id'))

    op.drop_table('shelf_levels')
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelves_name'))

    op.drop_table('shelves')
    # ### end Alembic commands ###
