"""add user permissions columns

Revision ID: f65c14090ffe
Revises: e5457c4cbd26
Create Date: 2026-06-22 10:32:41.227573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65c14090ffe'
down_revision = 'e5457c4cbd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_dashboard', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('can_manage_locations', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('can_manage_equipments', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('can_manage_almoxarifado', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_manage_users')
        batch_op.drop_column('can_manage_almoxarifado')
        batch_op.drop_column('can_manage_equipments')
        batch_op.drop_column('can_manage_locations')
        batch_op.drop_column('can_view_dashboard')

    # ### end Alembic commands ###
